server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://192.168.49.2:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://192.168.49.2:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://192.168.49.2:1003
    cart:
      path: /cart/**
      url: http://192.168.49.2:1004/api/v1
